version: '3.9'

services:
    statbench:
        image: php-cli-statbench-dev:latest
        build:
            context: .
            dockerfile: Dockerfile
            #target: production
        volumes:
            - .:/app
        #entrypoint: [""]
