name: CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v4
            - name: PHPUnit (php-actions)
              uses: php-actions/phpunit@v1
              with:
                  configuration: phpunit.xml.dist
